package com.myteam.modalissue;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Line implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Product")
	private java.lang.String product;
	@org.kie.api.definition.type.Label(value = "Price")
	private java.lang.Double price;
	@org.kie.api.definition.type.Label(value = "Quantity")
	private java.lang.Integer quantity;
	@org.kie.api.definition.type.Label(value = "Total")
	private java.lang.Double total;

	public Line() {
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.Integer quantity) {
		this.quantity = quantity;
	}

	public java.lang.Double getTotal() {
		return this.total;
	}

	public void setTotal(java.lang.Double total) {
		this.total = total;
	}

	public Line(java.lang.String product, java.lang.Double price,
			java.lang.Integer quantity, java.lang.Double total) {
		this.product = product;
		this.price = price;
		this.quantity = quantity;
		this.total = total;
	}

}